spring:
  # 配置DataSource tensorboard --logdir=./logs --host=192.168.0.31
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/model?useUnicode=true&characterEncoding=utf-8
      username: root
      password: 147258369
# 配置MyBatis
mybatis:
  check-config-location: true
  mapper-locations: classpath:mappers/*.xml